### ISSUE TITLE
Property 'websockets' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>'

### ISSUE THREAD

**Issue by dialexo** [graasp/graasp-plugin-websockets#19]
When the `graasp-websockets` plugin is installed as a dependency, types are not discovered by the compiler.

As a result, the Typescript compiler will complain that the `websockets` property cannot be found when destructuring the `websockets` property from the Fastify instance:

```ts
// in this example, we register behaviour from another plugin
const plugin = async (fastify, options) => {
  const { websockets } = fastify;
};
```

Outside of `graasp` core, this will generate the following error:

```
Property 'websockets' does not exist on type 'FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>'.
```

### Workaround fix 

As a workaround, consumers of the plugin outside of the `graasp` repository (such as other plugins with a separate codebase) must redeclare the `fastify` module augmentation in their own codebase:

```ts
// hack to force compiler to discover websockets service
declare module 'fastify' {
  interface FastifyInstance {
    websockets?: WebSocketService;
  }
}
const plugin = async (fastify, options) => {
  // 'websockets' should now be available on 'fastify'
  const { websockets } = fastify;
};
```

### Attempted fixes

Importing the types directly from the `src` folder may result in unrelated compilation errors (Typescript will try to compile the `graasp-websockets` plugin itself, and will not find its dependencies).

Another attempt consisted in using a dummy `loadTypes` function defined at `src/index.ts`, but the types would not be discovered either.

### Possible solution

The types could be added to `graasp-types`, but since the websockets are a plugin, I'm not convinced that adding them to the core types repository is a great idea. Besides, it shouldn't be required to use `.d.ts` definitions when writing purely Typescript code. The issue comes from the fact that there is no way to force the compiler to discover the `declare module 'fastify'` augmentation (except by adding the module folder manually to the local `tsconfig.json` of the consumer project).

**Comment by mochiruntime** [comment]
The issue was probably coming from mismatched fastify versions: all repos MUST be pinned to the exact same versions for the type augmentation to work. 

This is solved by lifting the types up to https://github.com/graasp/graasp-sdk anyway
